Question 1:
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [9]:
#Solution

# Import numpy package
import numpy as np

# Function
# vanderMondeMatrix () Parameters: inputVector,n,boolArg 
# @inputVector : arrayLike 1-D input array. 
# @n : int, optional Number of columns in the output.
# @boolArg : bool, If True, the powers increase from left to right, if False they are reversed.

#Returns: ndarray

# numpy vander() Parameters: x,N,increasing 
# @x : arrayLike 1-D input array. 
# @N : int, optional Number of columns in the output. If N is not specified, a square array is returned (N = len(x)).
# @increasing : bool, optional Order of the powers of the columns.
#    If True, the powers increase from left to right, if False (the default) they are reversed.

def vanderMondeMatrix(inputVector,n,boolArg):
    return np.vander(x=inputVector,N=n,increasing=boolArg)

# Example
inputVector = np.array([1, 2, 3, 5])
n = 5

# function execution
trueMatrix = vanderMondeMatrix(inputVector,n,True)

falseMatrix = vanderMondeMatrix(inputVector,n,False)

#output
print("Input vector",inputVector)
print("Result, when boolean argument is True: \n",trueMatrix)
print("Result, when boolean argument is False: \n",falseMatrix)

Input vector [1 2 3 5]
Result, when boolean argument is True: 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   5  25 125 625]]
Result, when boolean argument is False: 
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [625 125  25   5   1]]
